#!/bin/bash

set -e
file="/sys/class/backlight/acpi_video0/brightness"
current=$(cat "$file")
new="$current"
[ "$1" = "-inc" ] && new=$(( current + $2 ))
[ "$1" = "-dec" ] && new=$(( current - $2 ))
echo "$new"
echo "$new" > "$file"
