#!/bin/bash

xrandr --output HDMI-A-0 --primary --mode 1920x1080 --rate 60 --output DisplayPort-1 --mode 1920x1080 --rate 60 --right-of HDMI-A-0 --output DisplayPort-0 --mode 1920x1080 --rate 60 --rotate left --left-of HDMI-A-0
